server {
    listen 8000;
    server_name localhost;
    root ./public;
    client_max_body_size 10485760;

    location / {
        root ./public;
        index index.html;
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        root ./public;
        allow_methods GET POST DELETE;
        upload_store ./uploads;
        autoindex on;
    }

    location /uploads {
        root ./public;
        allow_methods GET POST DELETE;
        upload_store ./uploads;
        autoindex on;
    }

    location /list {
        root ./uploads;
        allow_methods GET;
        autoindex on;
    }

    location /redirect {
        root ./public;
        allow_methods GET;
        autoindex off;
    }

    location /alias {
        root ./public;
        allow_methods GET;
        autoindex off;
    }
}